-- AlterTable
ALTER TABLE "pokemon" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "poke_id" DROP NOT NULL,
ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "moves" DROP NOT NULL,
ALTER COLUMN "abilities" DROP NOT NULL,
ALTER COLUMN "users" DROP NOT NULL;

-- AlterTable
ALTER TABLE "user" ALTER COLUMN "username" DROP NOT NULL,
ALTER COLUMN "password" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "age" DROP NOT NULL;
